import { BSU_MAX_CONTRIBUTION, STAMP_DUTY_RATE, DEFAULT_DOWN_PAYMENT_RATE } from './finance'
import type { Inputs } from '../types'

export const DEFAULT_INPUTS: Inputs = {
  monthlyRent: 12000,
  rentIncrease: 2,
  purchasePrice: 4000000,
  downPayment: Math.round(4000000 * DEFAULT_DOWN_PAYMENT_RATE),
  mortgageRate: 5.5,
  loanTermYears: 25,
  monthlyHoaFee: 3000,
  stampDuty: Math.round(4000000 * STAMP_DUTY_RATE),
  brokerSellingFee: 100000,
  years: 10,
  appreciationRate: 2.5,
  investmentReturn: 5,
  contentsInsurance: 2400,
  electricity: 12000,
  internet: 6000,
  parking: 0,
  otherClosingCosts: 5000,
  sharedDebt: 0,
  municipalFees: 8000,
  renovationPct: 1,
  homeInsurance: 5000,
  propertyTax: 0,
  hoaFeeIncrease: 3,
  sharedDebtRate: 5.0,
  sharedDebtTermYears: 25,
  isBorettslag: false,
  interestOnlyYears: 0,
  mortgageRateChangeYear: 0,
  mortgageRateAfterChange: 4.5,
  isCouple: false,
  inflation: 2.5,
  savingsAccountBalance: 200000,
  savingsAccountRate: 4.0,
  askBalance: 400000,
  askRate: 7.0,
  askShieldingRate: 3.0,
  bsuActive: false,
  bsuYearlyContribution: BSU_MAX_CONTRIBUTION,
}
