export const WEALTH_TAX_THRESHOLD = 1_700_000

export const WEALTH_TAX_RATE = 1.0

export const PRIMARY_RESIDENCE_VALUATION = 0.25
export const PRIMARY_RESIDENCE_HIGH_THRESHOLD = 10_000_000
export const PRIMARY_RESIDENCE_HIGH_VALUATION = 0.70

export const SAVINGS_VALUATION = 1.0

export const FINANCIAL_ASSET_VALUATION = 0.80

export const INTEREST_DEDUCTION = 0.22

export const SAVINGS_TAX_RATE = 0.22

export const ASK_TAX_RATE = 0.3784

export const QUICK_INVESTMENT_TAX = 0.22

export const SECURITY_DEPOSIT_MONTHS = 3

export const BSU_TAX_DEDUCTION_RATE = 0.10
export const BSU_MAX_CONTRIBUTION = 27_500
